export enum TicketError {
    ITEMS_MUST_BE_PROVIDED = 'ITEMS_MUST_BE_PROVIDED',
    DENTIST_INFO_INVALID = 'DENTIST_INFO_INVALID',
    CANNOT_FIND_TICKET = 'CANNOT_FIND_TICKET',
    TICKET_WAS_DONE = 'TICKET_WAS_DONE',
    QTY_MUST_BE_THAN_MORE_ONE = 'QTY_MUST_BE_THAN_MORE_ONE'
}