export enum CalendarDentistError {
    CANNOT_FINT_CALENDAR_DENTIST = 'CANNOT_FINT_CALENDAR_DENTIST',
    START_TIME_MUST_BE_PROVIDED = 'START_TIME_MUST_BE_PROVIDED',
    END_TIME_MUST_BE_PROVIDED = 'END_TIME_MUST_BE_PROVIDED',
    CONTENT_MUST_BE_PROVIDED = 'CONTENT_MUST_BE_PROVIDED',
    TIME_INVALID_WITH_DIFERENT_CALENDAR = 'TIME_INVALID_WITH_DIFERENT_CALENDAR',
    INVALID_TIME = 'INVALID_TIME',
    DENTIST_INFO_INVALID = 'DENTIST_INFO_INVALID',
    INVALID_CALENDAR_STATUS = 'INVALID_CALENDAR_STATUS',
}