export enum ProductError {
    NAME_MUST_BE_PROVIDED = 'NAME_MUST_BE_PROVIDED',
    NAME_IS_EXISTED = 'NAME_IS_EXISTED',
    SUGGESTED_RETAILER_PRICE_MUST_BE_PROVIDED = 'SUGGESTED_RETAILER_PRICE_MUST_BE_PROVIDED',
    CANNOT_FIND_PRODUCT = 'CANNOT_FIND_PRODUCT',
    UNIT_MUST_BE_PROVIDED = 'UNIT_MUST_BE_PROVIDED'
}