export enum ServiceError {
    NAME_MUST_BE_PROVIDED = 'NAME_MUST_BE_PROVIDED',
    NAME_IS_EXISTED = 'NAME_IS_EXISTED',
    SUGGESTED_RETAILER_PRICE_MUST_BE_PROVIDED = 'SUGGESTED_RETAILER_PRICE_MUST_BE_PROVIDED',
}